---
- hosts: docker-machine
  remote_user: root

  tasks:
    - name: Run apt update
      apt:
        update_cache: yes
    - name: Install requirements
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: latest
    - name: Add Docker's GPG key
      shell: curl -fsSL https://download.docker.com/linux/debian/gpg | sudo apt-key add -
    - name: Add Docker repo
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/debian buster stable
        state: present
    - name: Run apt update
      apt:
        update_cache: yes
    - name: Install Docker engine
      apt:
        name:
         - docker-ce
         - docker-ce-cli
         - containerd.io